### PR TITLE
Fix BugZilla bug 1357

### PR DESCRIPTION
**Pull request by serebit**

### CODE REVIEW

**Comment by gouessej** [comment]
It's identical to the fix suggested by Giuseppe [https://jogamp.org/bugzilla/show_bug.cgi?id=1357#c10](https://jogamp.org/bugzilla/show_bug.cgi?id=1357#c10) suggested by me [https://jogamp.org/bugzilla/show_bug.cgi?id=1357#c5](https://jogamp.org/bugzilla/show_bug.cgi?id=1357#c5)

**Comment by gouessej** [comment]
@serebit https://sourceforge.net/p/jogl/code/ci/890efa2cbabaf2b99ecb37fb8c066d8fef172fdc/

**Comment by gouessej** [comment]
Don't merge this alone, it can cause regressions on other hardware: https://github.com/processing/processing/issues/5476

**Comment by gouessej** [comment]
Rather do this:
`final boolean isDriverMesa = glRenderer.contains(MesaSP) || glRenderer.contains("Gallium ") || (glVersion.contains(MesaSP) && glRenderer.contains("POLARIS"));`

**Comment by neilcsmith-net** [comment]
Also see https://github.com/processing/processing/issues/5476#issuecomment-463172485

**Comment by gouessej** [comment]
@neilcsmith-net https://jogamp.org/bugzilla/attachment.cgi?id=803

**Pull request merged**
